[FEAT] 톡 캘린더 일정 상세 조회 구현
kakao-tech-campus-2nd-step3/Team16_BE pull request #22
Opened 2024-10-02 00:15 UTC by KBM05haruin30

## 주요 변경사항
톡 캘린저 일정 상세 조회를 구현했습니다.

## 리뷰어에게...
톡 캘린더 일정 상세 조회를 구현하기 전에 rebase도 해보고 fetch도 해보고 pull도 해봤는데도 불구하고 이전 머지되었던 커밋이 남았습니다. 이 부분을 어떻게 해결해야 하는지 모르겠습니다.. 그래서 커밋 확인하실 때 'Merge branch week5'라고 쓰여진 부분 이후부터 확인해주시면 됩니다! 
아직 일정 상세 조회 테스트를 위해서 일정 생성하기 기능은 남겨두었는데, 지금 지우지 않고 추후에 지워도 될까요? 일정 생성 테스트는 제가 만든 api가 아닌 톡 캘린더 api에 직접 사용해도 추가는 되긴 합니다!

## 관련 이슈

closes #

## 체크리스트

- [X] `reviewers` 설정
- [X] `label` 설정

2024-10-02 06:24 UTC, ps9319 commented
pull을 upstream에서도 해보셨나요? upstream에서 하면 이전 커밋이 없어질 것 같아요

2024-10-02 08:01 UTC, KBM05haruin30 commented
이거 다음 pr에 한 번 해보겠습니다! fetch 후에 pull하는 것이 순서가 맞죠? 일단 fetch할 때 upstream을 하긴 했어요. 그 이후 인텔리제이에 있는 pull 버튼 눌러서 했었어요.

2024-10-02 11:11 UTC, speciling requested changes

2024-10-02 11:11 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
> +        }
이부분은 일정 목록 조회할때마다 상세조회 가능한 일정, Time, Location을 계속 중복으로 db에 저장하는 것 같은데 혹시 테스트 해 보셨나요?
어차피 일정 목록 조회하면 무조건 talkCalendarService.getEventList() 호출해서 톡캘린더에서 일정 목록 받아오니까 db에 일정 굳이 저장 안해도 될 것 같고, 저장하려면 기존에 저장됐던 일정인지 Event 엔티티의 kakaoEventId를 체크하는 로직이 필요해 보여요

2024-10-02 13:34 UTC, KBM05haruin30 commented on src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
> +        }
네, 지금 코드로는 중복으로 저장해두었습니다. 아직 저장에 대해서 명확히 정해진 것이 없어 일단 중복으로 저장을 했습니다. 굳이 저장 안 해도 될 것 같아서, 현재 어떻게 해결할지 민규님과 이야기 중이었습니다. 지금 이야기 나온 것은 캐싱을 사용하는 방법입니다. 캐싱에 대해서 어떻게 생각하시나요?

2024-10-02 16:25 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
> +        }
캐싱 사용하는것도 좋은 것 같아요!

2024-10-04 08:40 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
> +            eventCreateResponse);
새로운 리소스가 생성 되었으니 HttpStatus.CREATED가 더 적합하지 않을까요?
OK도 틀린건 아니지만 팀원들과 응답을 통일하면 좋을 것 같아서요!

2024-10-04 08:44 UTC, seojiu approved these changes

2024-10-04 10:19 UTC, speciling approved these changes

2024-10-04 10:22 UTC, KBM05haruin30 commented on src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
> +            eventCreateResponse);
확실히 새로운 리소스가 생성된 거니 CREATED가 더 적합할 것 같네요.

2024-10-04 10:23 UTC, ps9319 commented on src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
> +            eventCreateResponse);
동의합니다!

2024-10-04 10:26 UTC, ps9319 approved these changes

2024-10-04 10:26 UTC, ps9319 commented on src/main/java/org/cookieandkakao/babting/domain/calendar/dto/request/TimeCreateRequest.java
>      String endAt,
혹시 dto에서도 notnull이나 notblank와 같이 입력값 검증 하는 건 어떤가요!

2024-10-04 10:42 UTC, KBM05haruin30 commented on src/main/java/org/cookieandkakao/babting/domain/calendar/dto/request/TimeCreateRequest.java
>      String endAt,
좋은 것 같네요. 수정 후 다시 올리겠습니다!

2024-10-04 10:53 UTC, merged