[REFACTOR] 선호, 비선호 음식 CRUD 전략 패턴 적용
kakao-tech-campus-2nd-step3/Team16_BE pull request #24
Opened 2024-10-02 15:46 UTC by seojiu

## 주요 변경사항
전략패턴 적용했습니다. 
피드백 후에 테스트코드 작성하도록 하겠습니다.

## 리뷰어에게...

## 관련 이슈

closes #

## 체크리스트

- [ ] `reviewers` 설정
- [ ] `label` 설정

2024-10-03 07:09 UTC, speciling requested changes

2024-10-03 07:09 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +        }
지금 로직대로면 /api/auth 같은 선호 비선호 음식이랑 관련없는 곳에서도 uri를 잘못 적으면 Invalid preference type 이라는 메세지가 나가네요.
이부분은 404 Not Found에 맞는 메세지가 나가게 하거나, uri를 /api/preferences가 아니라 /api/food/preferences로 바꾸는 방법도 생각해보면 좋을것같아요

2024-10-03 07:09 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +        FoodPreferenceGetResponse response = strategy.addPreference(food);
foodRepositoryService에서 food 찾는건 서비스 계층으로 넘기는게 어떨까요?
각 strategy에서도 어차피 foodRepositoryService 사용하고 있기도 하고, 컨트롤러에서 entity를 직접 다루는건 좋지 않다고 들어서요

2024-10-03 07:09 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +        Food food = foodRepositoryService.findFoodById(request.foodId());
```suggestion
```
이건 불필요해 보이네요

2024-10-03 07:09 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/food/service/NonPreferenceFoodService.java
> +        nonPreferenceFoodRepository.deleteById(foodId);
이렇게 하면 foodId == nonPreferenceFoodId 인 NonPreferenceFood가 삭제될텐데 두 id는 서로 다르지 않나요?

2024-10-03 14:50 UTC, KBM05haruin30 commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +                "non-preference", nonPreferenceFoodService
제가 전략 패턴을 잘 몰라 궁금한 점이 있습니다! 이렇게 설정해두면 밑에 {type}에 "non-preference"의 값이 들어오면 자동으로 nonPreferenceFoodService를 사용하게 바뀌는 건가요?

2024-10-03 15:36 UTC, ps9319 commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodCategoryController.java
> +        return ApiResponseGenerator.success(HttpStatus.OK, "음식 카테고리 목록 조회 성공", categories);
오 저번에는 알아차리지 못했던 부분인데, 저는 항상 무슨 값이든 dto를 만들어서 return 해야겠다! 생각했었는데 생각해보니 String값들은 dto를 만들 필요가 없어보이네요 👍 👍 👍

2024-10-04 07:19 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +                "non-preference", nonPreferenceFoodService
네 맞습니다!

2024-10-04 07:52 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +        Food food = foodRepositoryService.findFoodById(request.foodId());
findFoodById 메서드에서 id가 존재하는지 예외처리 하기 때문에 넣었습니다. food를 찾는 기능을 서비스 계층으로 넘기면 이것도 같이 해결 될 것 같네요!

2024-10-04 07:52 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +        FoodPreferenceGetResponse response = strategy.addPreference(food);
동의합니다. 수정하겠습니다!

2024-10-04 07:52 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +        }
👌👌

2024-10-04 07:52 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/service/NonPreferenceFoodService.java
> +        nonPreferenceFoodRepository.deleteById(foodId);
제가 질문을 잘 이해 못 한 것 같습니다. 
nonPreferenceFoodRepository.deleteById(foodId);
를 실행했을때 NonPreferenceFood 엔티티를 삭제하는 것이 아니라, Food 엔티티를 잘못 삭제하는거냐고 질문하신거 맞나요?

2024-10-04 10:34 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/food/service/NonPreferenceFoodService.java
> +        nonPreferenceFoodRepository.deleteById(foodId);
여기서 foodId는 Food 엔티티의 id잖아요? 그런데 위 코드는 NonPreferenceFood 엔티티의 id가 Food의 id와 같은 NonPreferenceFood를 삭제하는 로직인 것 같아요.

 예를들어서 밥이라는 Food의 id가 1이고, 다른 사용자가 먼저 밥을 비선호 음식으로 등록해서 NonPreferenceFood의 id가 1이고, 현재 사용자가 밥을 비선호 음식으로 등록해서 NonPreferenceFood의 id가 2일때 저희가 원하는 기능은 id가 2번인 현재 사용자의 NonPreferenceFood가 삭제되는 거지만 지금 로직대로면 id가 1인 먼저 등록한 다른 사용자의 NonPreferenceFood가 삭제되버린다는거죠.

deleteById가 아니라 deleteByFoodId 가 돼야 한다고 생각합니다!

2024-10-04 10:47 UTC, ps9319 commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +        }
뭔가뭔가 여기도 어떤 전략인지 판별하는 과정에서 중복이 발생하는 것 같은데 따로 메서드로 빼거나 좋은 방법이 있을 것 같아요!!

2024-10-04 10:50 UTC, ps9319 commented on src/main/java/org/cookieandkakao/babting/domain/food/service/FoodRepositoryService.java
FoodService가 이미 있는데도 FoodRepositoryService를 따로 만드신 이유가 궁금해요!!

2024-10-04 10:58 UTC, ps9319 commented on src/main/java/org/cookieandkakao/babting/domain/food/service/NonPreferenceFoodService.java
> +        nonPreferenceFoodRepository.deleteById(foodId);
동의합니다!!

2024-10-04 11:01 UTC, ps9319 commented on src/main/java/org/cookieandkakao/babting/domain/food/service/NonPreferenceFoodService.java
> +        nonPreferenceFoodRepository.deleteById(foodId);
지금 preferenceFood 테이블에는
id, foodId, memberId가 있는데 

foodId로 삭제하려는 코드인 것 같은데 deleteById에 foodId를 넣게 되면 의도하지 않은대로 흘러갈 수 있을 것 같습니다.

2024-10-04 11:01 UTC, ps9319 commented
그리고 전략 패턴 도입 전 후 뭐가 달라졌는지도 궁금해요!
뭔가 더 편리해졌나요? 아니면 그냥 저냥인가요...?

2024-10-04 11:13 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/service/NonPreferenceFoodService.java
> +        nonPreferenceFoodRepository.deleteById(foodId);
아 이해했습니다. 리팩토링하면서 오류가 생겼네요. 수정했습니다!

2024-10-04 11:35 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/service/FoodRepositoryService.java
멘토님께서 예외 처리 로직들은 repository 그대로 쓰기보다 service로 래핑하면 좋을 것 같다고 하셔서 공통되는 메서드만 따로 빼서 만들어봤습니다.

2024-10-04 11:36 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +        }
메서드를 따로 빼는 것이 좋아보이네요! 감사합니다!

2024-10-04 12:02 UTC, seojiu commented
> 그리고 전략 패턴 도입 전 후 뭐가 달라졌는지도 궁금해요! 뭔가 더 편리해졌나요? 아니면 그냥 저냥인가요...?

반복되는 로직이 줄어서 훨씬 깔끔해진 것 같습니다. 특히 이름만 다른 똑같은 dto가 여러개라서 불편했는데 통일된 dto를 쓰니까 헷갈리지도 않고 좋네요!
전략이 2개 밖에 없어서 쓸지 말지 고민 많이 했는데 만들고 보니 유지보수하기 좋다는 생각이 들었습니다!

2024-10-04 12:15 UTC, KBM05haruin30 approved these changes

2024-10-04 13:01 UTC, speciling approved these changes

2024-10-04 13:03 UTC, merged