[FEAT] 모임별 선호/비선호 음식 CRUD 구현
kakao-tech-campus-2nd-step3/Team16_BE pull request #33
Opened 2024-10-11 13:19 UTC by seojiu

## 주요 변경사항
모임별 선호/비선호 음식 CRUD 구현
모임별 공통 선호 음식 찾기 구현

## 리뷰어에게...

## 관련 이슈

closes #

## 체크리스트

- [ ] `reviewers` 설정
- [ ] `label` 설정

2024-10-11 14:50 UTC, KBM05haruin30 commented on src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
> +    List<Member> findMembersByMeetingId(@Param("meetingId") Long meetingId);
제가 쿼리 어노테이션을 사용해 본 적이 없어서 질문 남깁니다! findMembersByMeetingId에 들어오는 meetingId 값으로 쿼리를 실행 시킨 후 나온 값을 List로 받아오는 것이 맞나요? 그리고 밑의 Param("meetingId")를 사용하신 이유가 궁금합니다!

2024-10-11 14:59 UTC, KBM05haruin30 requested changes

2024-10-11 14:59 UTC, KBM05haruin30 commented on src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
> +    List<Member> findMembersByMeetingId(@Param("meetingId") Long meetingId);
제가 쿼리 어노테이션을 사용해 본 적이 없어서 질문 남깁니다! findMembersByMeetingId에 들어오는 meetingId 값으로 쿼리를 실행 시킨 후 나온 값을 List로 받아오는 것이 맞나요? 그리고 밑의 Param("meetingId")를 사용하신 이유가 궁금합니다!

2024-10-11 14:59 UTC, KBM05haruin30 commented on src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceUpdater.java
> +        });
updatePreferences가 실행 될 때마다 모두 지우고 새로 추가하는 것 말고 다른 방법은 없었나요?? STEP2 때 모두 지우고 새로 추가하는 방법을 사용했었는데 그때 제 멘토님께서 비효율적이고 update에 안 어울린다고 말씀하셨었습니다.

2024-10-12 05:49 UTC, ps9319 commented on src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceUpdater.java
> +        });
음 저는 현재 코드가 더 적절해보이는게 모임만의 선호/비선호 음식을 수정해야할 때 원래 있던 값과 없던 값을 비교하는게 더 복잡할 것 같아요. 그래서 그냥 원래 거 전부 삭제하고 요청으로 들어온 값 전부 추가하는게 더 좋아보여요!!

2024-10-12 05:49 UTC, ps9319 commented on src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingPreferenceFoodService.java
> +                .collect(Collectors.toList());
MeetingPreferenceGetResponse 에 정팩메 추가하는 건 어떻게 생각하시나요!?

2024-10-12 05:49 UTC, ps9319 commented on src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingPreferenceService.java
> +    }
여기에 모임만의 선호/비선호 음식도 찾고 추가하는 내용이 추가돼야되죠??

2024-10-12 05:53 UTC, ps9319 approved these changes

2024-10-12 06:05 UTC, KBM05haruin30 approved these changes

2024-10-12 06:13 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +            return ApiResponseGenerator.success(HttpStatus.NO_CONTENT, "조회된 음식이 없습니다", null);
보민님이 구현하신 일정 조회 부분이랑 마찬가지로 선호/비선호 음식 조회시에도 OK 상태코드와 빈 리스트로 응답하는게 적절할 것 같아요

2024-10-12 06:13 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceController.java
> +        }
`/api/meeting/{meeting_id}/participants`
현재 코드대로라면 위 uri처럼 particapant에 접근하려다가 오타로 잘못 입력했을때도 Invalid preference type 이라는 응답이 나가게 될 것 같아요. preference type과는 관계없는 uri이니 일반적인 404 Not Found로 응답되는게 더 맞는데요.

2024-10-12 06:13 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceController.java
> +            return ApiResponseGenerator.success(HttpStatus.NO_CONTENT, "조회된 음식이 없습니다", null);
이부분도 OK에 빈 리스트면 좋을 것 같아요

2024-10-12 06:13 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceUpdater.java
> +        });
저도 동의합니다.
기존 선호/비선호 음식과 수정하려는 선호/비선호 음식들을 Set으로 만들어서 교집합은 놔두고, {기존}-{수정}은 삭제하고, {수정}-{기존}은 추가하는 방식으로 하면 어렵지 않게 할 수 있지 않을까요?

2024-10-12 06:14 UTC, speciling commented on src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceUpdater.java
> +        });
이부분은 멘토님께 질문드려봐도 좋을 것 같네요

2024-10-12 06:38 UTC, merged

2024-10-12 06:46 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceUpdater.java
> +        });
그럼 멘토님께 질문 드린 후 수정하겠습니다!

2024-10-12 06:50 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
> +    List<Member> findMembersByMeetingId(@Param("meetingId") Long meetingId);
네 맞습니다.  @Param("meetingId") 이거는 파라미터 이름이랑 메서드의 매개변수를 연결해 주기 위해 썼습니다. 생략하면 어느 값과 매핑해야 할지 몰라서 쿼리를 실행할 수 없을거예요!

2024-10-12 06:53 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingPreferenceFoodService.java
> +                .collect(Collectors.toList());
👍👍👍 적용해보겠습니다!

2024-10-12 06:56 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingPreferenceService.java
> +    }
MeetingNonPreferenceFoodRepository랑 MeetingPreferenceFoodRepository를 사용했어야하는데 preferenceFoodRepository랑 nonPreferenceFoodRepository를 사용해서 만들어버렸네요...!
개인 선호/비선호이 아니라 모임별 선호/비선호 음식을 처리하도록 수정하겠습니다!

2024-10-12 06:58 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
> +            return ApiResponseGenerator.success(HttpStatus.NO_CONTENT, "조회된 음식이 없습니다", null);
앗 제가 반대로 사용해버렸네요. 수정하겠습니다

2024-10-12 07:03 UTC, seojiu commented on src/main/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceController.java
> +        }
네넵. 예외처리가 부족했던 것 같네요. 수정하도록 하겠습니다.